-- ============================================================================
-- SIRAJ – RLS Remediation
-- Closes data-leakage gaps left by earlier migrations.
-- Safe to run multiple times (all statements are idempotent).
-- ============================================================================

-- ── 1. Drop any USING (true) open policies ───────────────────────────────────

DROP POLICY IF EXISTS "Enable read access for all users" ON public.rfqs;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.suppliers;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.rfq_invites;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.responses;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.categories;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.category_suppliers;

-- Generic catch-all names sometimes generated by Supabase Studio
DROP POLICY IF EXISTS "Allow all" ON public.rfqs;
DROP POLICY IF EXISTS "Allow all" ON public.suppliers;
DROP POLICY IF EXISTS "Allow all" ON public.rfq_invites;
DROP POLICY IF EXISTS "Allow all" ON public.responses;
DROP POLICY IF EXISTS "Allow all" ON public.categories;
DROP POLICY IF EXISTS "Allow all" ON public.category_suppliers;

-- ── 2. Ensure RLS is ON everywhere ───────────────────────────────────────────

ALTER TABLE public.rfqs              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rfq_invites       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.responses         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.category_suppliers ENABLE ROW LEVEL SECURITY;

-- ── 3. rfqs ───────────────────────────────────────────────────────────────────
-- Owned directly via user_id column.

DROP POLICY IF EXISTS rfqs_user_policy ON public.rfqs;

CREATE POLICY rfqs_user_policy ON public.rfqs
  FOR ALL
  USING     (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ── 4. suppliers ─────────────────────────────────────────────────────────────
-- Owned directly via user_id column.

DROP POLICY IF EXISTS suppliers_user_policy ON public.suppliers;

CREATE POLICY suppliers_user_policy ON public.suppliers
  FOR ALL
  USING     (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ── 5. rfq_invites ───────────────────────────────────────────────────────────
-- No direct user_id — ownership derived through the parent rfq.
-- Suppliers accessing their invite via token use a separate public route
-- (no auth.uid()), so that path is handled in application logic, not here.

DROP POLICY IF EXISTS invites_user_policy ON public.rfq_invites;

CREATE POLICY invites_user_policy ON public.rfq_invites
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.rfqs
      WHERE rfqs.id      = rfq_invites.rfq_id
        AND rfqs.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.rfqs
      WHERE rfqs.id      = rfq_invites.rfq_id
        AND rfqs.user_id = auth.uid()
    )
  );

-- ── 6. responses ─────────────────────────────────────────────────────────────
-- No direct user_id — ownership derived through the parent rfq.
-- Supplier INSERT on the public form is handled via service-role in the
-- API route; authenticated buyers only ever SELECT/DELETE their own.

DROP POLICY IF EXISTS responses_user_policy ON public.responses;

CREATE POLICY responses_user_policy ON public.responses
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.rfqs
      WHERE rfqs.id      = responses.rfq_id
        AND rfqs.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.rfqs
      WHERE rfqs.id      = responses.rfq_id
        AND rfqs.user_id = auth.uid()
    )
  );

-- ── 7. categories ────────────────────────────────────────────────────────────
-- Owned directly via user_id column (added by categories_rls.sql).

DROP POLICY IF EXISTS "Users own categories" ON public.categories;

CREATE POLICY "Users own categories" ON public.categories
  FOR ALL
  USING     (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ── 8. category_suppliers ────────────────────────────────────────────────────
-- No direct user_id — ownership derived through the parent category.

DROP POLICY IF EXISTS "Users own category_suppliers" ON public.category_suppliers;

CREATE POLICY "Users own category_suppliers" ON public.category_suppliers
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.categories
      WHERE categories.id      = category_suppliers.category_id
        AND categories.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.categories
      WHERE categories.id      = category_suppliers.category_id
        AND categories.user_id = auth.uid()
    )
  );
